// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4bNNbfe3rE34KbIKdNEKp12vPioocN_c',
    appId: '1:35293989527:web:6bdeccc001d7510a5377d2',
    messagingSenderId: '35293989527',
    projectId: 'coco-seal',
    authDomain: 'coco-seal.firebaseapp.com',
    storageBucket: 'coco-seal.firebasestorage.app',
    measurementId: 'G-GJC50PKPV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGeAc88wjN60eZGs9A5o-A-7383bJCpto',
    appId: '1:35293989527:android:97324a139698fb6a5377d2',
    messagingSenderId: '35293989527',
    projectId: 'coco-seal',
    storageBucket: 'coco-seal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmbz6aEu5Kgbn-SLdi9pbOimRZigw3iC4',
    appId: '1:35293989527:ios:b1b69b6029a338715377d2',
    messagingSenderId: '35293989527',
    projectId: 'coco-seal',
    storageBucket: 'coco-seal.firebasestorage.app',
    iosBundleId: 'com.CocoSeal.cocoSeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmbz6aEu5Kgbn-SLdi9pbOimRZigw3iC4',
    appId: '1:35293989527:ios:b1b69b6029a338715377d2',
    messagingSenderId: '35293989527',
    projectId: 'coco-seal',
    storageBucket: 'coco-seal.firebasestorage.app',
    iosBundleId: 'com.CocoSeal.cocoSeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4bNNbfe3rE34KbIKdNEKp12vPioocN_c',
    appId: '1:35293989527:web:b85a49728d2c35705377d2',
    messagingSenderId: '35293989527',
    projectId: 'coco-seal',
    authDomain: 'coco-seal.firebaseapp.com',
    storageBucket: 'coco-seal.firebasestorage.app',
    measurementId: 'G-CMPMX4C8XD',
  );

}